config/routes.rb
Rails.application.routes.draw do
  get 'assessment_blogs/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'assessments/index'
  get 'contact' => 'contact#new'
  get 'contact/create'
  get 'contact/destroy'
  get 'partners/index'
  get 'cnewses/index'
  get 'researchs/index'
  get 'entrepreneurships/index'
  get 'clibraries/index'
  get 'about' => 'about#index', as: 'about'
  
  resources :clibraries
  resources :cnewses
  resources :entrepreneurships
  resources :researchs
  resources :partners
  resources :assessments
  #resources :cnews, only: [:index]
  root 'about#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
    has_many :assessment_blogs

end

app/models/assessment_blog.rb
class AssessmentBlog < ApplicationRecord
    belongs_to :assessment
end

app/models/entrepereneurship.rb
class Entrepereneurship < ApplicationRecord
    has_many :entrepreneurship_blogs
end

app/models/entrepreneurship.rb
class Entrepreneurship < ApplicationRecord
    has_many :entrepreneurship_blogs
end

app/models/entrepreneurship_blog.rb
class EntrepreneurshipBlog < ApplicationRecord

    belongs_to :entrepreneurship
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/cnewses_controller.rb
class CnewsesController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessment_blogs_helper.rb
module AssessmentBlogsHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/clibraries_helper.rb
module ClibrariesHelper
end

app/helpers/cnewses_helper.rb
module CnewsesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/researchs_helper.rb
module ResearchsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "partials/navigation" %>
    <div class="container" id="container">
        <%= yield %>     
    </div><!-- /.container -->
      <%= render  "partials/footer" %> 
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer text-center">
<div class="container">
    <div class="col-md-8 footer-content">
      <h3 class="page-header">Usefull Links</h3>
      <li class="list-unstyled"><%= link_to  "About us", root_path %></li>
      <li class="list-unstyled"><%= link_to  "Innovation", entrepreneurship_path(2) %></li>
      <li class="list-unstyled"><%= link_to  "Creativity", entrepreneurship_path(1) %></li>
    </div>
    <div class=" col-md-4 pull-right">
       <h3 class="page-header">Follow us on Social Media</h3>
          <a href="https://www.facebook.com/Ezno9-1629675853803658/?ref=br_tf" class="btn btn-primary"><i class="fab fa-facebook-f"></i></a>
          <a href="https://www.twitter.com/eznobaboa" class="btn btn-primary"><i class="fab fa-twitter"></i></a>
          <a href="https://www.instagram.com/ezno9/" class="btn btn-primary"><i class="fab fa-instagram"></i></a>
          <a href="https://www.linkedin.com/in/ezno9" class="btn btn-primary"><i class="fab fa-linkedin"></i></a>
          <a href="https://www.youtube.com/channel/UC8TuNR5lRpmPi87oxdGPu1g/featured?view_as=subscriber" class="btn btn-primary"><i class="fab fa-youtube"></i></a>
          <h3 class="page-header">Address</h3>
          <div class="panel-default">
            <div class="panel-body text-left">
               <strong>Location: </strong>KN 2 st, Ave 2 <br/>
               <strong>Telephone: </strong>+250784735963<br/>
               <strong>Email: </strong>nivierlos@gmail.com<br/>
               <h5>Visit us in working hour fron Monday to Friday</h5>
            </div>
          </div>
    </div> 
</div>
    <hr>
    <p>&copy; Career Library | Allright Reserved</p>
</footer>

app/views/partials/_navigation.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Career</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] =='about' ? 'active' : '' %>"><%= link_to  "About us", root_path %></li>
            <li class=" dropdown <%= params[:controller] == 'clibraries' ? 'active' : ''%>"><%= link_to  "Career Library", clibraries_path, class:'dropdown-toggle', 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">Innovation</a></li>
                        <li><a href="#">Creativity</a></li>
                        <li><a href="#">Technology</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                    </ul>
                </div>
            </div>
          </ul>
            </li>
            <li class=" dropdown <%= params[:controller] == 'cnewses' ? 'active' : ''%>"><%= link_to  "Career Blog", cnewses_path, class:'dropdown-toggle', 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">Innovation</a></li>
                        <li><a href="#">Creativity</a></li>
                        <li><a href="#">Technology</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                    </ul>
                </div>
            </div>
          </ul>
            </li>
            <li class=" dropdown <%= params[:controller] == 'entrepreneurships' ? 'active' : ''%>"><%= link_to  "Entrepreneurship", entrepreneurships_path, class:'dropdown-toggle', 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <% if @entrepreneurships.exists? %>
              <% @entrepreneurships.each do |eship| %> 
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><%= link_to  eship.name, entrepreneurship_path(eship) %></li>
                    </ul>
                </div>
                <% end %>
                <% else %>
                <p></p>
                <% end %>  
            </div>
          </ul>
            </li>
            <li class=" dropdown <%= params[:controller] == 'researchs' ? 'active' : ''%>"><%= link_to  "Research", researchs_path, class:'dropdown-toggle', 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">Innovation</a></li>
                        <li><a href="#">Creativity</a></li>
                        <li><a href="#">Technology</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">Link</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                        <li><a href="#">link</a></li>
                    </ul>
                </div>
            </div>
          </ul>
            </li>

            <li class=" dropdown <%= params[:controller] == 'assessments' ? 'active' : ''%>"><%= link_to  "Assessment", assessments_path, class:'dropdown-toggle', 'data-toggle' => 'dropdown' %>
            <ul class="dropdown-menu multi-column columns-2">
            <div class="row">
                <% if @assessments.exists? %>
                <% @assessments.each do |assessment| %> 
                <div class="col-md-4">
                    <ul class="multi-column-dropdown list-unstyled">
                        <li><%= link_to  assessment.name, assessment_path(assessment) %></li>
                    </ul>
                </div>
                <% end %>
                <% else %>
                <p></p>
                <% end %>
            </div>
          </ul>
            </li><!-- End of Assessment -->
            <li class="<%= params[:controller] == 'partners' ? 'active' : '' %>"><%= link_to  "Our partners", partners_path %></li>
            <li class="<%= params[:controller] == 'contact' ? 'active' : '' %>"><%= link_to  "Contact us", contact_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>